### ISSUE TITLE
Recommended Projector?

### ISSUE THREAD

**Issue by rbock52** [cgre-aachen/open_AR_Sandbox#16]
I am in the process of converting an old AR sandbox that was built using the UC Davis's Blue prints. I am having trouble aligning the topographic map on the sand and I was wondering if it is because of the projector that I am using? I am using a short throw projector that projects at a right angle. What projector are you using?

**Comment by SimonVirgo** [comment]
Hello @rbock52,
Open-AR Sandbox currently does not compensate for perspective distortion, so the recommended setup is putting the  projector and sensor as close together as possible, ideally right over the middle of the sandbox. Also, the higher the distance between the projector and the sand surface the better the alignment will be, but of course that comes with the disadvantage of losing resolution in the sandbox. 
My recommendations would be to move the projector closer to the sensor in your setup. using a short throw projector that means that you probably have to angle it down a bit to have the sandbox in view. If you do that, make sure that you set the keystone correction so that the projected image in the sandbox is square. 
 
We have tested the following projectors with very good results: 
Beamer Epson EB U42
BenQ MW632ST

If you need to buy a new projector I would recommend the Epson EF-100W. this is an affordable laser projector (=long living   and bright light source) at a very small form factor.

Let me know how it works out!
All the best
-Simon

**Comment by rbock52** [comment]
Hi Simon,

Thanks for the response! I have the BenQ MW632ST projector. It took a little bit to get it set up, but I think it is aligned now! 

- I moved the projector closer to the middle of the sandbox and angled it down so that it fits the sandbox. 
- I also had to move the projector higher up as I increased the angle of the projector.

-Ryan
