### ISSUE TITLE
adding sea-level contour works exactly once...

### ISSUE THREAD

**Issue by flohorovicic** [cgre-aachen/open_AR_Sandbox#17]
In new branch: https://github.com/cgre-aachen/open_AR_Sandbox/tree/fw_sea_level_poly_patches

Adding polygon patch works - also with holes, etc. I also added a widget checkbox to activate the feature. It also works that the level can then be changed with the slider.

However: when it is unticked, then it can not be activated again. Also, the normal sea level vis (through colourmap) does then not work anymore. 

Any idea, @danielsk78 ? 

<img width="311" alt="image" src="https://user-images.githubusercontent.com/1070677/102691849-d6c35400-420f-11eb-9c74-cbd2a5db6045.png">

**Comment by danielsk78** [comment]
The thread is stopped because an error appears. And now is just skipping the TopoModule from the MainThread loop.
Traceback (most recent call last):
...
line 134, in remove self._remove_method(self)
ValueError: list.remove(x): x not in list

Problem is solved with the latest commit:
How to solve the problem: self.sea_level_patch was already empty but still existing in memory. So just set self.sea_level_patch = None when is removed for the first time.

**Comment by flohorovicic** [comment]
Awesome, thanks!

**Comment by flohorovicic** [comment]
I'll add a couple more features and create a new pull request for the polygon plot.

**Comment by flohorovicic** [comment]
Issue solved
